
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  flask_app:
    build: ./flask_app
    ports:
      - "5001:5000"
    depends_on:
      - keycloak

volumes:
  keycloak_data:

